### ISSUE TITLE
rake bing_token:get[my_token.json,your_dev_token,your_bing_client_id] not working

### ISSUE THREAD

**Issue by markblasdls** [Effilab/bing_ads_ruby_sdk#71]
Tried to run rake bing_token:get[my_token.json,your_dev_token,your_bing_client_id] but it returns 

```
rake aborted!
Don't know how to build task 'bing_token:get' (See the list of available tasks with `rake --tasks`)
```

Did try to copy rake file to my project task directory and id did run but returns 
`invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.`

Sometimes it has error `unauthorized_client: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?`

What should be the correct steps to generate token?

**Comment by danielmbarlow** [comment]
Thanks for your feedback @markblasdls . Is this the same issue as #51 ?

**Comment by markblasdls** [comment]
@danielmbarlow  I think yes but I already updated to latest version and still rake is missing.

**Comment by danielmbarlow** [comment]
The changes referred to in #51 haven't been released yet, sorry. I'm trying to get a little time to create a release for it.

For now I'll close this issue in favour of #51. Feel free to reopen the issue if it's not the same problem
