### ISSUE TITLE
How to use the reporting service with bing_ads_ruby_sdk?

### ISSUE THREAD

**Issue by jipiboily** [Effilab/bing_ads_ruby_sdk#82]
Hello folks,

It doesn't look like there is a forum, Discord or anything, so I'm asking here.

I've looked through the code ( https://github.com/Effilab/bing_ads_ruby_sdk/blob/adf0fba04d968bf2528783270c22dbf2dc708b81/lib/bing_ads_ruby_sdk/services/reporting.rb ), and it's unclear to me so far how to make use of the reporting services through your gem.

Would it be possible to get an example of code that works or some documentation around it?

Maybe it's just because I'm very rusty with SOAP, but we can't figure it out so far, even getting a decent error message from the API response isn't really clear.

What worked for us is getting a list of accounts:

```ruby
@api = BingAdsRubySdk::Api.new(oauth_store: @store,
  developer_token: ENV["MICROSOFT_ADVERTISING_DEVELOPER_TOKEN"],
  client_id: ENV["MICROSOFT_ADVERTISING_CLIENT_ID"],
  client_secret: ENV['MICROSOFT_ADVERTISING_SECRET_VALUE'])

@store.write({access_token: access_token, refresh_token: refresh_token,
  expires_in: expires_in, expires_at: expires_at, issued_at: token_issued_at})
@api.customer_management.find_accounts_or_customers_info(filter: "", top_n: 1000)
```

This all works fine.

But when trying to fetch a report, as there is no doc, we decided to create our own XML query like this (maybe wrongly so):

```ruby
xml_query = <<~XML
<ReportRequest type="AccountPerformanceReportRequest" i:nil="false" i:type="-- derived type specified here with the appropriate prefix --">
  <Aggregation>Summary</Aggregation>
  <Columns i:nil="false">
    <AccountPerformanceReportColumn>AccountName</AccountPerformanceReportColumn>
    <AccountPerformanceReportColumn>Clicks</AccountPerformanceReportColumn>
  </Columns>
  <Scope i:nil="false">
    <AccountIds i:nil="false" xmlns:a1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
      <a1:long>OUR_ACCOUNT_ID</a1:long>
    </AccountIds>
  </Scope>
  <Time i:nil="false">
    <CustomDateRangeEnd i:nil="false">
      <Day>25</Day>
      <Month>4</Month>
      <Year>2023</Year>
    </CustomDateRangeEnd>
    <CustomDateRangeStart i:nil="false">
      <Day>1</Day>
      <Month>5</Month>
      <Year>2023</Year>
    </CustomDateRangeStart>
  </Time>
</ReportRequest>
XML```

and call it with:

```ruby
begin
  res = @api.reporting.call(:submit_generate_report, report_request: xml_query)
rescue => ex
  p ex
  puts ex.message
  raise
end
```

Sadly, we are getting a pretty generic error:

```
/Users/.../.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bing_ads_ruby_sdk-1.5.2/lib/bing_ads_ruby_sdk/errors/error_handler.rb:15:in `call': Bing Ads API error - The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs. (BingAdsRubySdk::Errors::GeneralError)
```

Any idea how we could get a report to get generated? Or to get the details about the error?

Thanks so much

**Comment by danielmbarlow** [comment]
@jipiboily it looks like control over the message detail is on the Microsoft side, so perhaps you could ask them what the details of the problem are.

Just in case it's something in the XML, have you tried something like this?

```ruby
request = {
  account_performance_report_request: {
    aggregation: "Summary"
    ...
  }
}
@api.reporting.call(:submit_generate_report, request)
```

**Comment by jipiboily** [comment]
Thanks so much quick reply + the doc PR; this will help a ton for sure!

We'll have a shot at it this week and will report back for sure .

**Comment by danielmbarlow** [comment]
@jipiboily We just merged some improved documentation into the README in `master`. Please could you check it out and let us know if it works for you?

If all is well, let's close this issue.

**Comment by jipiboily** [comment]
We had to move to something else, but we'll be back soon. There were a thing or two not working exactly as-is, but we'll submit a PR if that's still the case with the updated doc.

Thanks so much!

**Comment by danielmbarlow** [comment]
Thanks @jipiboily . We look forwards to that PR. Thanks for your feedback

**Comment by jipiboily** [comment]
Just FYI, your updates before merging were precisely the ones I had to do on my end. All works as documented. Thanks so much! :)
