### ISSUE TITLE
Release new version of gem

### ISSUE THREAD

**Issue by dyakubovich** [Effilab/bing_ads_ruby_sdk#89]
Hi, could you please release new version of gem? Because latest version  doesn't include this changes https://github.com/Effilab/bing_ads_ruby_sdk/pull/79 

I know, that I can set `branch: 'master'`  in the my Gemfile, but it is not best practise 

Thank you

**Comment by dyakubovich** [comment]
@danielmbarlow could you help please?

**Comment by tdutreui-solocal** [comment]
Hi,
Sorry for missing your comments, we will release in the near future.
Please also note that as Ruby 2 is no longer maintained, we will also drop support for it for the next release

**Comment by danielmbarlow** [comment]
Sorry @dyakubovich. We'll deal with that soon.

**Comment by tdutreui-solocal** [comment]
@dyakubovich v1.6 is released, feel free to try it and close this issue if it's all good for you

**Comment by dyakubovich** [comment]
Thank you
